#
# Module manifest for module 'MicrosoftTeams'
#
# Generated by: Microsoft Corporation
#
# Updated on: 6/30/2020
#

@{
# Script module or binary module file associated with this manifest.
RootModule = './MicrosoftTeams.psm1'

# Version number of this module.
ModuleVersion = '4.9.1'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd910df43-3ca6-4c9c-a2e3-e9f45a8e2ad9'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.

For more information, please visit the following: https://docs.microsoft.com/MicrosoftTeams/teams-powershell-overview'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# Removed this script from here because this module is used in SAW machines as well where Contraint Language Mode is on.
# Because of CLM constraint we were not able to import Teams module to SAW machines, that is why removing this script.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
#NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =  @(
   'Clear-CsOnlineTelephoneNumberOrder'
	,'Complete-CsOnlineTelephoneNumberOrder'
	,'Disable-CsMeetingRoom'
	,'Disable-CsOnlineSipDomain'
#preview	,'Disable-CsTeamsShiftsConnectionErrorReport'
	,'Enable-CsOnlineSipDomain'
	,'Export-CsAutoAttendantHolidays'
	,'Export-CsOnlineAudioFile'
	,'Find-CsGroup'
	,'Find-CsOnlineApplicationInstance'
	,'Get-CsApplicationAccessPolicy'
	,'Get-CsApplicationMeetingConfiguration'
	,'Get-CsAutoAttendant'
	,'Get-CsAutoAttendantHolidays'
	,'Get-CsAutoAttendantStatus'
	,'Get-CsAutoAttendantSupportedLanguage'
	,'Get-CsAutoAttendantSupportedTimeZone'
	,'Get-CsAutoAttendantTenantInformation'
	,'Get-CsBatchPolicyAssignmentOperation'
	,'Get-CsCallingLineIdentity'
	,'Get-CsCallQueue'
	,'Get-CsCloudCallDataConnection'
	,'Get-CsDialPlan'
	,'Get-CsEffectiveTenantDialPlan'
	,'Get-CsExternalAccessPolicy'
	,'Get-CsGroupPolicyAssignment'
	,'Get-CsHybridTelephoneNumber'
	,'Get-CsInboundBlockedNumberPattern'
	,'Get-CsInboundExemptNumberPattern'
	,'Get-CsMeetingMigrationStatus'
	,'Get-CsOnlineApplicationInstance'
	,'Get-CsOnlineApplicationInstanceAssociation'
	,'Get-CsOnlineApplicationInstanceAssociationStatus'
	,'Get-CsOnlineAudioConferencingRoutingPolicy'
	,'Get-CsOnlineAudioFile'
	,'Get-CsOnlineDialInConferencingBridge'
	,'Get-CsOnlineDialInConferencingLanguagesSupported'
	,'Get-CsOnlineDialinConferencingPolicy'
	,'Get-CsOnlineDialInConferencingServiceNumber'
	,'Get-CsOnlineDialinConferencingTenantConfiguration'
	,'Get-CsOnlineDialInConferencingTenantSettings'
	,'Get-CsOnlineDialInConferencingUser'
	,'Get-CsOnlineDialOutPolicy'
	,'Get-CsOnlineDirectoryTenant'
	,'Get-CsOnlineEnhancedEmergencyServiceDisclaimer'
	,'Get-CsOnlineLisCivicAddress'
	,'Get-CsOnlineLisLocation'
	,'Get-CsOnlineLisPort'
	,'Get-CsOnlineLisSubnet'
	,'Get-CsOnlineLisSwitch'
	,'Get-CsOnlineLisWirelessAccessPoint'
	,'Get-CsOnlinePowerShellEndpoint'
	,'Get-CsOnlinePSTNGateway'
	,'Get-CsOnlinePstnUsage'
	,'Get-CsOnlineSchedule'
	,'Get-CsOnlineSipDomain'
	,'Get-CsOnlineTelephoneNumber'
	,'Get-CsOnlineTelephoneNumberCountry'
	,'Get-CsOnlineTelephoneNumberOrder'
	,'Get-CsOnlineTelephoneNumberType'
	,'Get-CsOnlineUser'
	,'Get-CsOnlineVoicemailUserSettings'
	,'Get-CsOnlineVoiceRoute'
	,'Get-CsOnlineVoiceRoutingPolicy'
	,'Get-CsOnlineVoiceUser'
	,'Get-CsPhoneNumberAssignment'
	,'Get-CsPolicyPackage'
	,'Get-CsPrivacyConfiguration'
	,'Get-CsTeamsAcsFederationConfiguration'
	,'Get-CsTeamsAppPermissionPolicy'
	,'Get-CsTeamsAppSetupPolicy'
	,'Get-CsTeamsAudioConferencingPolicy'
	,'Get-CsTeamsCallHoldPolicy'
	,'Get-CsTeamsCallingPolicy'
	,'Get-CsTeamsCallParkPolicy'
	,'Get-CsTeamsClientConfiguration'
	,'Get-CsTeamsComplianceRecordingApplication'
	,'Get-CsTeamsComplianceRecordingPolicy'
	,'Get-CsTeamsCortanaPolicy'
	,'Get-CsTeamsEducationAssignmentsAppPolicy'
	,'Get-CsTeamsEducationConfiguration'
	,'Get-CsTeamsEmergencyCallingPolicy'
	,'Get-CsTeamsEmergencyCallRoutingPolicy'
	,'Get-CsTeamsEnhancedEncryptionPolicy'
	,'Get-CsTeamsFilesPolicy'
	,'Get-CsTeamsGuestCallingConfiguration'
	,'Get-CsTeamsGuestMeetingConfiguration'
	,'Get-CsTeamsGuestMessagingConfiguration'
	,'Get-CsTeamsIPPhonePolicy'
	,'Get-CsTeamsMediaLoggingPolicy'
	,'Get-CsTeamsMeetingBroadcastConfiguration'
	,'Get-CsTeamsMeetingBroadcastPolicy'
	,'Get-CsTeamsEventsPolicy'
	,'Get-CsTeamsMeetingConfiguration'
	,'Get-CsTeamsMigrationConfiguration'
	,'Get-CsTeamsMobilityPolicy'
	,'Get-CsTeamsNetworkRoamingPolicy'
	,'Get-CsTeamsNotificationAndFeedsPolicy'
	,'Get-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Get-CsTeamsShiftsAppPolicy'
	,'Get-CsTeamsShiftsConnectionConnector'
	,'Get-CsTeamsShiftsConnectionErrorReport'
	,'Get-CsTeamsShiftsConnectionInstance'
	,'Get-CsTeamsShiftsConnectionOperation'
	,'Get-CsTeamsShiftsConnectionSyncResult'
	,'Get-CsTeamsShiftsConnectionTeamMap'
	,'Get-CsTeamsShiftsConnectionWfmTeam'
	,'Get-CsTeamsShiftsConnectionWfmUser'
	,'Get-CsTeamsShiftsPolicy'
	,'Get-CsTeamsSurvivableBranchAppliance'
	,'Get-CsTeamsSurvivableBranchAppliancePolicy'
	,'Get-CsTeamsTargetingPolicy'
	,'Get-CsTeamsTranslationRule'
	,'Get-CsTeamsUnassignedNumberTreatment'
	,'Get-CsTeamsUpgradeConfiguration'
	,'Get-CsTeamsUpgradePolicy'
	,'Get-CsTeamsVdiPolicy'
	,'Get-CsTeamsVideoInteropServicePolicy'
	,'Get-CsTeamsVoiceApplicationsPolicy'
	,'Get-CsTeamsWorkLoadPolicy'
	,'Get-CsTeamTemplate'
	,'Get-CsTeamTemplateList'
	,'Get-CsTenant'
	,'Get-CsTenantBlockedCallingNumbers'
	,'Get-CsTenantDialPlan'
	,'Get-CsTenantFederationConfiguration'
	,'Get-CsTenantLicensingConfiguration'
	,'Get-CsTenantMigrationConfiguration'
	,'Get-CsTenantNetworkConfiguration'
	,'Get-CsTenantNetworkRegion'
	,'Get-CsTenantNetworkSite'
	,'Get-CsTenantNetworkSubnet'
	,'Get-CsTenantTrustedIPAddress'
	,'Get-CsUserCallingSettings'
	,'Get-CsUserPolicyAssignment'
	,'Get-CsUserPolicyPackage'
	,'Get-CsUserPolicyPackageRecommendation'
	,'Get-CsVideoInteropServiceProvider'
	,'Grant-CsApplicationAccessPolicy'
	,'Grant-CsCallingLineIdentity'
	,'Grant-CsDialoutPolicy'
	,'Grant-CsExternalAccessPolicy'
	,'Grant-CsGroupPolicyPackageAssignment'
	,'Grant-CsOnlineAudioConferencingRoutingPolicy'
	,'Grant-CsOnlineVoicemailPolicy'
	,'Grant-CsOnlineVoiceRoutingPolicy'
	,'Grant-CsTeamsAppPermissionPolicy'
	,'Grant-CsTeamsAppSetupPolicy'
	,'Grant-CsTeamsAudioConferencingPolicy'
	,'Grant-CsTeamsCallHoldPolicy'
	,'Grant-CsTeamsCallingPolicy'
	,'Grant-CsTeamsCallParkPolicy'
	,'Grant-CsTeamsChannelsPolicy'
	,'Grant-CsTeamsComplianceRecordingPolicy'
	,'Grant-CsTeamsCortanaPolicy'
	,'Grant-CsTeamsEmergencyCallingPolicy'
	,'Grant-CsTeamsEmergencyCallRoutingPolicy'
	,'Grant-CsTeamsEnhancedEncryptionPolicy'
	,'Grant-CsTeamsFeedbackPolicy'
	,'Grant-CsTeamsFilesPolicy'
	,'Grant-CsTeamsIPPhonePolicy'
	,'Grant-CsTeamsMediaLoggingPolicy'
	,'Grant-CsTeamsMeetingBroadcastPolicy'
	,'Grant-CsTeamsEventsPolicy'
	,'Grant-CsTeamsMeetingPolicy'
	,'Grant-CsTeamsMessagingPolicy'
	,'Grant-CsTeamsMobilityPolicy'
	,'Grant-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Grant-CsTeamsShiftsPolicy'
	,'Grant-CsTeamsSurvivableBranchAppliancePolicy'
	,'Grant-CsTeamsUpdateManagementPolicy'
	,'Grant-CsTeamsUpgradePolicy'
	,'Grant-CsTeamsVdiPolicy'
	,'Grant-CsTeamsVideoInteropServicePolicy'
	,'Grant-CsTeamsVoiceApplicationsPolicy'
	,'Grant-CsTeamsWorkLoadPolicy'
	,'Grant-CsTenantDialPlan'
	,'Grant-CsUserPolicyPackage'
	,'Import-CsAutoAttendantHolidays'
	,'Import-CsOnlineAudioFile'
	,'Invoke-CsInternalPSTelemetry'
	,'Move-CsInternalHelper'
	,'New-CsApplicationAccessPolicy'
	,'New-CsAutoAttendant'
	,'New-CsAutoAttendantCallableEntity'
	,'New-CsAutoAttendantCallFlow'
	,'New-CsAutoAttendantCallHandlingAssociation'
	,'New-CsAutoAttendantDialScope'
	,'New-CsAutoAttendantMenu'
	,'New-CsAutoAttendantMenuOption'
	,'New-CsAutoAttendantPrompt'
	,'New-CsBatchPolicyAssignmentOperation'
	,'New-CsBatchPolicyPackageAssignmentOperation'
	,'New-CsCallingLineIdentity'
	,'New-CsCallQueue'
	,'New-CsCloudCallDataConnection'
	,'New-CsCustomPolicyPackage'
	,'New-CsEdgeAllowAllKnownDomains'
	,'New-CsEdgeAllowList'
	,'New-CsEdgeDomainPattern'
	,'New-CsExternalAccessPolicy'
	,'New-CsGroupPolicyAssignment'
	,'New-CsHybridTelephoneNumber'
	,'New-CsInboundBlockedNumberPattern'
	,'New-CsInboundExemptNumberPattern'
	,'New-CsOnlineApplicationInstance'
	,'New-CsOnlineApplicationInstanceAssociation'
	,'New-CsOnlineAudioConferencingRoutingPolicy'
	,'New-CsOnlineDateTimeRange'
	,'New-CsOnlineLisCivicAddress'
	,'New-CsOnlineLisLocation'
	,'New-CsOnlinePSTNGateway'
	,'New-CsOnlineSchedule'
	,'New-CsOnlineTelephoneNumberOrder'
	,'New-CsOnlineTimeRange'
	,'New-CsOnlineVoiceRoute'
	,'New-CsOnlineVoiceRoutingPolicy'
	,'New-CsTeamsAudioConferencingPolicy'
	,'New-CsTeamsCallHoldPolicy'
	,'New-CsTeamsCallingPolicy'
	,'New-CsTeamsCallParkPolicy'
	,'New-CsTeamsComplianceRecordingApplication'
	,'New-CsTeamsComplianceRecordingPairedApplication'
	,'New-CsTeamsComplianceRecordingPolicy'
	,'New-CsTeamsCortanaPolicy'
	,'New-CsTeamsEmergencyCallingPolicy'
	,'New-CsTeamsEmergencyCallRoutingPolicy'
	,'New-CsTeamsEmergencyNumber'
	,'New-CsTeamsEnhancedEncryptionPolicy'
	,'New-CsTeamsFilesPolicy'
	,'New-CsTeamsIPPhonePolicy'
	,'New-CsTeamsMeetingBroadcastPolicy'
	,'New-CsTeamsEventsPolicy'
	,'New-CsTeamsMobilityPolicy'
	,'New-CsTeamsNetworkRoamingPolicy'
	,'New-CsTeamsRoomVideoTeleConferencingPolicy'
	,'New-CsTeamsShiftsConnectionBatchTeamMap'
	,'New-CsTeamsShiftsConnectionInstance'
	,'New-CsTeamsShiftsConnectionTeamMap'
	,'New-CsTeamsShiftsPolicy'
	,'New-CsTeamsSurvivableBranchAppliance'
	,'New-CsTeamsSurvivableBranchAppliancePolicy'
	,'New-CsTeamsTranslationRule'
	,'New-CsTeamsUnassignedNumberTreatment'
	,'New-CsTeamsVdiPolicy'
	,'New-CsTeamsVoiceApplicationsPolicy'
	,'New-CsTeamsWorkLoadPolicy'
	,'New-CsTeamTemplate'
	,'New-CsTenantDialPlan'
	,'New-CsTenantNetworkRegion'
	,'New-CsTenantNetworkSite'
	,'New-CsTenantNetworkSubnet'
	,'New-CsTenantTrustedIPAddress'
	,'New-CsUserCallingDelegate'
	,'New-CsVideoInteropServiceProvider'
	,'New-CsVoiceNormalizationRule'
	,'Register-CsOnlineDialInConferencingServiceNumber'
	,'Remove-CsApplicationAccessPolicy'
	,'Remove-CsAutoAttendant'
	,'Remove-CsCallingLineIdentity'
	,'Remove-CsCallQueue'
	,'Remove-CsCustomPolicyPackage'
	,'Remove-CsExternalAccessPolicy'
	,'Remove-CsGroupPolicyAssignment'
	,'Remove-CsHybridTelephoneNumber'
	,'Remove-CsInboundBlockedNumberPattern'
	,'Remove-CsInboundExemptNumberPattern'
	,'Remove-CsOnlineApplicationInstanceAssociation'
	,'Remove-CsOnlineAudioConferencingRoutingPolicy'
	,'Remove-CsOnlineAudioFile'
	,'Remove-CsOnlineDialInConferencingTenantSettings'
	,'Remove-CsOnlineLisCivicAddress'
	,'Remove-CsOnlineLisLocation'
	,'Remove-CsOnlineLisPort'
	,'Remove-CsOnlineLisSubnet'
	,'Remove-CsOnlineLisSwitch'
	,'Remove-CsOnlineLisWirelessAccessPoint'
	,'Remove-CsOnlinePSTNGateway'
	,'Remove-CsOnlineSchedule'
	,'Remove-CsOnlineTelephoneNumber'
	,'Remove-CsOnlineVoiceRoute'
	,'Remove-CsOnlineVoiceRoutingPolicy'
	,'Remove-CsPhoneNumberAssignment'
	,'Remove-CsTeamsAppPermissionPolicy'
	,'Remove-CsTeamsAppSetupPolicy'
	,'Remove-CsTeamsAudioConferencingPolicy'
	,'Remove-CsTeamsCallHoldPolicy'
	,'Remove-CsTeamsCallingPolicy'
	,'Remove-CsTeamsCallParkPolicy'
	,'Remove-CsTeamsComplianceRecordingApplication'
	,'Remove-CsTeamsComplianceRecordingPolicy'
	,'Remove-CsTeamsCortanaPolicy'
	,'Remove-CsTeamsEmergencyCallingPolicy'
	,'Remove-CsTeamsEmergencyCallRoutingPolicy'
	,'Remove-CsTeamsEnhancedEncryptionPolicy'
	,'Remove-CsTeamsFilesPolicy'
	,'Remove-CsTeamsIPPhonePolicy'
	,'Remove-CsTeamsMeetingBroadcastPolicy'
	,'Remove-CsTeamsEventsPolicy'
	,'Remove-CsTeamsMobilityPolicy'
	,'Remove-CsTeamsNetworkRoamingPolicy'
	,'Remove-CsTeamsNotificationAndFeedsPolicy'
	,'Remove-CsTeamsRoomVideoTeleConferencingPolicy'
    ,'Remove-CsTeamsShiftsConnectionInstance'
    ,'Remove-CsTeamsShiftsConnectionTeamMap'
	,'Remove-CsTeamsShiftsPolicy'
	,'Remove-CsTeamsShiftsScheduleRecord'
	,'Remove-CsTeamsSurvivableBranchAppliance'
	,'Remove-CsTeamsSurvivableBranchAppliancePolicy'
	,'Remove-CsTeamsTargetingPolicy'
	,'Remove-CsTeamsTranslationRule'
	,'Remove-CsTeamsUnassignedNumberTreatment'
	,'Remove-CsTeamsVdiPolicy'
	,'Remove-CsTeamsVoiceApplicationsPolicy'
	,'Remove-CsTeamsWorkLoadPolicy'
	,'Remove-CsTeamTemplate'
	,'Remove-CsTenantDialPlan'
	,'Remove-CsTenantNetworkRegion'
	,'Remove-CsTenantNetworkSite'
	,'Remove-CsTenantNetworkSubnet'
	,'Remove-CsTenantTrustedIPAddress'
	,'Remove-CsUserCallingDelegate'
	,'Remove-CsVideoInteropServiceProvider'
	,'Set-CsApplicationAccessPolicy'
	,'Set-CsApplicationMeetingConfiguration'
	,'Set-CsAutoAttendant'
	,'Set-CsCallingLineIdentity'
	,'Set-CsCallQueue'
	,'Set-CsExternalAccessPolicy'
	,'Set-CsInboundBlockedNumberPattern'
	,'Set-CsInboundExemptNumberPattern'
	,'Set-CsInternalOnlinePowerShellEndpoint'
	,'Set-CsOnlineApplicationInstance'
	,'Set-CsOnlineAudioConferencingRoutingPolicy'
	,'Set-CsOnlineDialInConferencingBridge'
	,'Set-CsOnlineDialInConferencingServiceNumber'
	,'Set-CsOnlineDialInConferencingTenantSettings'
	,'Set-CsOnlineDialInConferencingUser'
	,'Set-CsOnlineDialInConferencingUserDefaultNumber'
	,'Set-CsOnlineEnhancedEmergencyServiceDisclaimer'
	,'Set-CsOnlineLisCivicAddress'
	,'Set-CsOnlineLisLocation'
	,'Set-CsOnlineLisPort'
	,'Set-CsOnlineLisSubnet'
	,'Set-CsOnlineLisSwitch'
	,'Set-CsOnlineLisWirelessAccessPoint'
	,'Set-CsOnlinePSTNGateway'
	,'Set-CsOnlinePstnUsage'
	,'Set-CsOnlineSchedule'
	,'Set-CsOnlineVoiceApplicationInstance'
	,'Set-CsOnlineVoicemailUserSettings'
	,'Set-CsOnlineVoiceRoute'
	,'Set-CsOnlineVoiceRoutingPolicy'
	,'Set-CsOnlineVoiceUser'
	,'Set-CsPhoneNumberAssignment'
	,'Set-CsPrivacyConfiguration'
	,'Set-CsTeamsAcsFederationConfiguration'
	,'Set-CsTeamsAudioConferencingPolicy'
	,'Set-CsTeamsCallHoldPolicy'
	,'Set-CsTeamsCallingPolicy'
	,'Set-CsTeamsCallParkPolicy'
	,'Set-CsTeamsClientConfiguration'
	,'Set-CsTeamsComplianceRecordingApplication'
	,'Set-CsTeamsComplianceRecordingPolicy'
	,'Set-CsTeamsCortanaPolicy'
	,'Set-CsTeamsEducationAssignmentsAppPolicy'
	,'Set-CsTeamsEducationConfiguration'
	,'Set-CsTeamsEmergencyCallingPolicy'
	,'Set-CsTeamsEmergencyCallRoutingPolicy'
	,'Set-CsTeamsEnhancedEncryptionPolicy'
	,'Set-CsTeamsFilesPolicy'
	,'Set-CsTeamsGuestCallingConfiguration'
	,'Set-CsTeamsGuestMeetingConfiguration'
	,'Set-CsTeamsGuestMessagingConfiguration'
	,'Set-CsTeamsIPPhonePolicy'
	,'Set-CsTeamsMeetingBroadcastConfiguration'
	,'Set-CsTeamsMeetingBroadcastPolicy'
	,'Set-CsTeamsEventsPolicy'
	,'Set-CsTeamsMeetingConfiguration'
	,'Set-CsTeamsMigrationConfiguration'
	,'Set-CsTeamsMobilityPolicy'
	,'Set-CsTeamsNetworkRoamingPolicy'
	,'Set-CsTeamsNotificationAndFeedsPolicy'
	,'Set-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Set-CsTeamsShiftsAppPolicy'
 	,'Set-CsTeamsShiftsConnectionInstance'
	,'Set-CsTeamsShiftsPolicy'
	,'Set-CsTeamsSurvivableBranchAppliance'
	,'Set-CsTeamsSurvivableBranchAppliancePolicy'
	,'Set-CsTeamsTargetingPolicy'
	,'Set-CsTeamsTranslationRule'
	,'Set-CsTeamsUnassignedNumberTreatment'
	,'Set-CsTeamsUpgradeConfiguration'
	,'Set-CsTeamsVdiPolicy'
	,'Set-CsTeamsVoiceApplicationsPolicy'
	,'Set-CsTeamsWorkLoadPolicy'
	,'Set-CsTenantBlockedCallingNumbers'
	,'Set-CsTenantDialPlan'
	,'Set-CsTenantFederationConfiguration'
	,'Set-CsTenantMigrationConfiguration'
	,'Set-CsTenantNetworkRegion'
	,'Set-CsTenantNetworkSite'
	,'Set-CsTenantNetworkSubnet'
	,'Set-CsTenantTrustedIPAddress'
	,'Set-CsUser'
	,'Set-CsUserCallingDelegate'
	,'Set-CsUserCallingSettings'
	,'Set-CsVideoInteropServiceProvider'
	,'Start-CsExMeetingMigration'
	,'Sync-CsOnlineApplicationInstance'
	,'Test-CsEffectiveTenantDialPlan'
	,'Test-CsInboundBlockedNumberPattern'
    ,'Test-CsTeamsShiftsConnectionValidate'
	,'Test-CsTeamsTranslationRule'
	,'Test-CsTeamsUnassignedNumberTreatment'
	,'Test-CsVoiceNormalizationRule'
	,'Unregister-CsOnlineDialInConferencingServiceNumber'
	,'Update-CsAutoAttendant'
	,'Update-CsCustomPolicyPackage'
	,'Update-CsTeamsShiftsConnectionInstance'
	,'Update-CsTeamTemplate'
	,'New-CsBatchTeamsDeployment'
	,'Get-CsBatchTeamsDeploymentStatus'
#OCE related functions exports start here. DO NOT MODIFY!
    ,'Set-CsOCEContext'
    ,'Clear-CsOCEContext'
    ,'Get-CsMeetingMigrationTransactionHistory'
	,'Get-CsMasVersionedSchemaData'
	,'Get-CsBusinessVoiceDirectoryDiagnosticData'
	,'Get-CsCloudTenant'
	,'Get-CsCloudUser'
	,'Get-CsHostingProvider'
    ,'Set-CsBackfillHydrate'
#OCE exports end
)
# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'Add-TeamChannelUser'
    ,'Add-TeamUser'
    ,'Connect-MicrosoftTeams'
    ,'Disconnect-MicrosoftTeams'
	,'Get-AssociatedTeam'
    ,'Get-MultiGeoRegion'
    ,'Get-Operation'
	,'Get-SharedWithTeam'
	,'Get-SharedWithTeamUser'
    ,'Get-Team'
	,'Get-TeamAllChannel'
    ,'Get-TeamChannel'
    ,'Get-TeamChannelUser'
	,'Get-TeamIncomingChannel'
    ,'Get-TeamsApp'
    ,'Get-TeamUser'
	,'Get-CsTeamsMessagingPolicy'
	,'Get-CsTeamsMeetingPolicy'
	,'Get-CsOnlineVoicemailPolicy'
    ,'Get-CsTeamsFeedbackPolicy'
    ,'Get-CsTeamsUpdateManagementPolicy'
    ,'Get-CsTeamsChannelsPolicy'
    ,'New-Team'
    ,'New-TeamChannel'
    ,'New-TeamsApp'
	,'New-CsTeamsMessagingPolicy'
	,'New-CsTeamsMeetingPolicy'
	,'New-CsOnlineVoicemailPolicy'
    ,'New-CsTeamsFeedbackPolicy'
    ,'New-CsTeamsUpdateManagementPolicy'
    ,'New-CsTeamsChannelsPolicy'
	,'Remove-SharedWithTeam'
    ,'Remove-Team'
    ,'Remove-TeamChannel'
    ,'Remove-TeamChannelUser'
    ,'Remove-TeamsApp'
    ,'Remove-TeamUser'
	,'Remove-CsTeamsMessagingPolicy'
	,'Remove-CsTeamsMeetingPolicy'
	,'Remove-CsOnlineVoicemailPolicy'
    ,'Remove-CsTeamsFeedbackPolicy'
    ,'Remove-CsTeamsUpdateManagementPolicy',
    ,'Remove-CsTeamsChannelsPolicy'
    ,'Set-Team'
    ,'Set-TeamArchivedState'
    ,'Set-TeamChannel'
    ,'Set-TeamPicture'
    ,'Set-TeamsApp'
	,'Set-CsTeamsMessagingPolicy'
	,'Set-CsTeamsMeetingPolicy'
	,'Set-CsOnlineVoicemailPolicy'
    ,'Set-CsTeamsFeedbackPolicy'
    ,'Set-CsTeamsUpdateManagementPolicy'
    ,'Set-CsTeamsChannelsPolicy'
#preview    ,'Add-TeamsAppInstallation'
#preview    ,'Get-TeamsAppInstallation'
    ,'Get-TeamTargetingHierarchyStatus'
#preview    ,'Remove-TeamsAppInstallation'
    ,'Remove-TeamTargetingHierarchy'
    ,'Set-TeamTargetingHierarchy'
#preview    ,'Update-TeamsAppInstallation'
#preview    ,'Get-LicenseReportForChangeNotificationSubscription'
 )

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Office365', 'MicrosoftTeams', 'Teams'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/MicrosoftDocs/office-docs-powershell/master/teams/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams'

        # A URL to an icon representing this module.
        IconUri = 'https://statics.teams.microsoft.com/evergreen-assets/apps/teamscmdlets_largeimage.png'

        # Appends prerelease string to version
        Prerelease = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
 **4.9.1-GA** (The project - MicrosoftTeams contains changes till this release)
- Releases Application-based authentication support in Connect-MicrosoftTeams in GA. More details in https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-application-authentication.
- Contains a new implementation of [New|Get|Set|Remove]-CsTeamsChannelsPolicy and [New|Get|Set|Remove]-CsTeamsUpdateManagementPolicy. Functionality remains the same as previous implementation.
- Adds UseNewTeamsClient parameter to TeamsUpdateManagementPolicy.
- Adds EnablePrivateTeamDiscovery parameter to TeamsChannelsPolicy.
- Fixes issues with authentication token not refreshing for some policy cmdlets.
- Fixes issues where display format was broken for some cmdlets.
- Adds SipProxyAddress, TeamsMediaLoggingPolicy, CountryAbbreviation, UserValidationErrors and WhenCreated attributes in Get-CsOnlineUser output when run without -Identity parameter. Out of these attributes, CountryAbbreviation, UserValidationErros and WhenCreated will not show any values yet. These will be gradually rolled out, more details in https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser.
- The complete release notes can be found in the below link:
https://docs.microsoft.com/MicrosoftTeams/teams-powershell-release-notes
'@
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIInvwYJKoZIhvcNAQcCoIInsDCCJ6wCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBrtmal0ExU/Gyj
# QYAEdu93A+fa576jeSEoKSFe1Xq80qCCDXYwggX0MIID3KADAgECAhMzAAACy7d1
# OfsCcUI2AAAAAALLMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjIwNTEyMjA0NTU5WhcNMjMwNTExMjA0NTU5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC3sN0WcdGpGXPZIb5iNfFB0xZ8rnJvYnxD6Uf2BHXglpbTEfoe+mO//oLWkRxA
# wppditsSVOD0oglKbtnh9Wp2DARLcxbGaW4YanOWSB1LyLRpHnnQ5POlh2U5trg4
# 3gQjvlNZlQB3lL+zrPtbNvMA7E0Wkmo+Z6YFnsf7aek+KGzaGboAeFO4uKZjQXY5
# RmMzE70Bwaz7hvA05jDURdRKH0i/1yK96TDuP7JyRFLOvA3UXNWz00R9w7ppMDcN
# lXtrmbPigv3xE9FfpfmJRtiOZQKd73K72Wujmj6/Su3+DBTpOq7NgdntW2lJfX3X
# a6oe4F9Pk9xRhkwHsk7Ju9E/AgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUrg/nt/gj+BBLd1jZWYhok7v5/w4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzQ3MDUyODAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAJL5t6pVjIRlQ8j4dAFJ
# ZnMke3rRHeQDOPFxswM47HRvgQa2E1jea2aYiMk1WmdqWnYw1bal4IzRlSVf4czf
# zx2vjOIOiaGllW2ByHkfKApngOzJmAQ8F15xSHPRvNMmvpC3PFLvKMf3y5SyPJxh
# 922TTq0q5epJv1SgZDWlUlHL/Ex1nX8kzBRhHvc6D6F5la+oAO4A3o/ZC05OOgm4
# EJxZP9MqUi5iid2dw4Jg/HvtDpCcLj1GLIhCDaebKegajCJlMhhxnDXrGFLJfX8j
# 7k7LUvrZDsQniJZ3D66K+3SZTLhvwK7dMGVFuUUJUfDifrlCTjKG9mxsPDllfyck
# 4zGnRZv8Jw9RgE1zAghnU14L0vVUNOzi/4bE7wIsiRyIcCcVoXRneBA3n/frLXvd
# jDsbb2lpGu78+s1zbO5N0bhHWq4j5WMutrspBxEhqG2PSBjC5Ypi+jhtfu3+x76N
# mBvsyKuxx9+Hm/ALnlzKxr4KyMR3/z4IRMzA1QyppNk65Ui+jB14g+w4vole33M1
# pVqVckrmSebUkmjnCshCiH12IFgHZF7gRwE4YZrJ7QjxZeoZqHaKsQLRMp653beB
# fHfeva9zJPhBSdVcCW7x9q0c2HVPLJHX9YCUU714I+qtLpDGrdbZxD9mikPqL/To
# /1lDZ0ch8FtePhME7houuoPcMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGZ8wghmbAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAALLt3U5+wJxQjYAAAAAAsswDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEILqZz8+FVMSLNUZRMqKKFRzR
# IztMzQyLe58hJfibG+A8MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAaTv+7ByBZF7iv9zdV4j6sywu0oDe17khI4+VFXIcupv/yic6C9WrLBVi
# F/gDqqD/FuLA6IMfV1HUuAWyX6TBMx0GQBV9qZdtNmEI2hS5xmBzS+c5vEABQsmj
# 0Q1jmzx9cDSX3CpOCgqdM1KalrY4Gd0dFYSY/Yqqtvj+k4Dydj6udGgmL7q7ObBl
# trhNJEzfePSi8khSF8Aba6zDKIbJROVJbzAPZzVdvqE05cRuMR0NPloqrlU4Z23N
# bal2XUuGQok5WoyIvzqV00Uqb2/IjfhiJPQZsVIrfoLhBSK5OhalDkgeUEDkYkfc
# f354WxlvYefA7mE88E/lf20VB18dFaGCFykwghclBgorBgEEAYI3AwMBMYIXFTCC
# FxEGCSqGSIb3DQEHAqCCFwIwghb+AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsq
# hkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCB7UGxiclopqj+H1WLobbf5x9wNLVXakx0d39sNJadjRwIGY2xVoV5V
# GBMyMDIyMTExNTEwMTIzMC4wMzZaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNO
# Ojg2REYtNEJCQy05MzM1MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
# ZXJ2aWNloIIReDCCBycwggUPoAMCAQICEzMAAAG3IScaB6IqhkYAAQAAAbcwDQYJ
# KoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjIw
# OTIwMjAyMjE0WhcNMjMxMjE0MjAyMjE0WjCB0jELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3Bl
# cmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjo4NkRGLTRC
# QkMtOTMzNTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMf9z1dQNBNkTBq3HJclypjQ
# cJIlDAgpvsw4vHJe06n532RKGkcn0V7p65OeA1wOoO+8NsopnjPpVZ8+4s/RhdMC
# MNPQJXoWdkWOp/3puIEs1fzPBgTJrdmzdyUYzrAloICYx722gmdpbNf3P0y5Z2gR
# O48sWIYyYeNJYch+ZfJzXqqvuvq7G8Nm8IMQi8Zayvx+5dSGBM5VYHBxCEjXF9EN
# 6Qw7A60SaXjKjojSpUmpaM4FmVec985PNdSh8hOeP2tL781SBan92DT19tfNHv9H
# 0FAmE2HGRwizHkJ//mAZdS0s6bi/UwPMksAia5bpnIDBOoaYdWkV0lVG5rN0+ltR
# z9zjlaH9uhdGTJ+WiNKOr7mRnlzYQA53ftSSJBqsEpTzCv7c673fdvltx3y48Per
# 6vc6UR5e4kSZsH141IhxhmRR2SmEabuYKOTdO7Q/vlvAfQxuEnJ93NL4LYV1IWw8
# O+xNO6gljrBpCOfOOTQgWJF+M6/IPyuYrcv79Lu7lc67S+U9MEu2dog0MuJIoYCM
# iuVaXS5+FmOJiyfiCZm0VJsJ570y9k/tEQe6aQR9MxDW1p2F3HWebolXj9su7zrr
# ElNlHAEvpFhcgoMniylNTiTZzLwUj7TH83gnugw1FCEVVh5U9lwNMPL1IGuz/3U+
# RT9wZCBJYIrFJPd6k8UtAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUs/I5Pgw0JAVh
# DdYB2yPII8l4tOwwHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYD
# VR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
# CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAA2dZMybhVxSXTbJ
# zFgvNiMCV5/Ayn5UuzJU495YDtcefold0ehR9QBGBhHmAMt10WYCHz2WQUyM3mQD
# 4IsHfEL1JEwgG9tGq71ucn9dknLBHD30JvbQRhIKcvFSnvRCCpVpilM8F/YaWXC9
# VibSef/PU2GWA+1zs64VFxJqHeuy8KqrQyfF20SCnd8zRZl4YYBcjh9G0GjhJHUP
# AYEx0r8jSWjyi2o2WAHD6CppBtkwnZSf7A68DL4OwwBpmFB3+vubjgNwaICS+fkG
# VvRnP2ZgmlfnaAas8Mx7igJqciqq0Q6An+0rHj1kxisNdIiTzFlu5Gw2ehXpLrl5
# 9kvsmONVAJHhndpx3n/0r76TH+3WNS9UT9jbxQkE+t2thif6MK5krFMnkBICCR/D
# VcV1qw9sg6sMEo0wWSXlQYXvcQWA65eVzSkosylhIlIZZLL3GHZD1LQtAjp2A5F7
# C3Iw4Nt7C7aDCfpFxom3ZulRnFJollPHb3unj9hA9xvRiKnWMAMpS4MZAoiV4O29
# zWKZdUzygp7gD4WjKK115KCJ0ovEcf92AnwMAXMnNs1o0LCszg+uDmiQZs5eR7jz
# dKzVfF1z7bfDYNPAJvm5pSQdby3wIOsN/stYjM+EkaPtUzr8OyMwrG+jpFMbsB4c
# fN6tvIeGtrtklMJFtnF68CcZZ5IAMIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJ
# mQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
# dGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1
# WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjK
# NVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhg
# fWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJp
# rx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/d
# vI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka9
# 7aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKR
# Hh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9itu
# qBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyO
# ArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItb
# oKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
# bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
# AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQW
# BBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacb
# UzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYz
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnku
# aHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
# QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2
# VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwu
# bWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
# MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
# XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6
# U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVt
# I1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis
# 9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTp
# kbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0
# sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138e
# W0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJ
# sWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7
# Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0
# dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
# tB1VM1izoXBm8qGCAtQwggI9AgEBMIIBAKGB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjo4
# NkRGLTRCQkMtOTMzNTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaIjCgEBMAcGBSsOAwIaAxUAyGdBGMObODlsGBZmSUX2oWgfqcaggYMwgYCk
# fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIF
# AOcda2QwIhgPMjAyMjExMTUwOTM1MzJaGA8yMDIyMTExNjA5MzUzMlowdDA6Bgor
# BgEEAYRZCgQBMSwwKjAKAgUA5x1rZAIBADAHAgEAAgIAvTAHAgEAAgIRWzAKAgUA
# 5x685AIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAID
# B6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GBABBGuioz/98UjFMF6a2U
# NIsvtEALkT9BVz7PZzyDjvhI4kvUgnUHlhkK+363lP9FBopO4ielcrMMvUu4SwgC
# d2DVZWE/D8o9IuRlqJAy2q6qivmPj8RFXZlWDOJjqbcAC7mhoAgrnWVWpuDez8ht
# 1UlFU7QYgAWLP4HJ3G5Q5vp+MYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgUENBIDIwMTACEzMAAAG3IScaB6IqhkYAAQAAAbcwDQYJYIZIAWUDBAIB
# BQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQx
# IgQg6XExyRmTOdFs4QnJQ27YEDGR3ZxhzLR25GmmHnwfoVcwgfoGCyqGSIb3DQEJ
# EAIvMYHqMIHnMIHkMIG9BCBsJ3jTsh7aL8hNeiYGL5/8IBn8zUfr7/Q7rkM8ic1w
# QTCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABtyEn
# GgeiKoZGAAEAAAG3MCIEINBjT1kydcyiLUlVnJNi8q3QdOLiNHNzXDatVoFr8Xqk
# MA0GCSqGSIb3DQEBCwUABIICAIXJsPen7n2WyBrBoZ/OkKGUS05mlN8RL/dgqG5Y
# kaO8mxH3IzdRN54kTmDR61B6CXOIixD9bbddhBrh6V55cpK9TynWxwf1QSzE4Sr1
# AGmSRY7q0xpHdow0JYBgN+wST3hRbzSVdaDp6VaTW+03mXDBq4/4iHV2z7gbowjz
# e09pYM5aMrAfXnby8DAy4fSK2TTGuHrAsdnpssDuIYymkCNpMYCkyxf+PSg4Qdcp
# WZlvjtnhGMI0MJwE2nrarbcKB/fiHsS94Y+LpH8nqqr21aFQg79uEGfaqwou7okl
# Gpd1ebnhZslBxRBmIQdFxY8J5Idt4Go1GM2xSXkaJP2HoiPVTzCQp9ccqT/P6h9H
# WVZP7Z3+Hl6pF/cgQnkRcBtc0ryNaxYXdNRjxjaoIFo44OVjMT7N4Uw/m2+zboJT
# xyxA0GDbXCNQ5j8QAGcZBnRut1HMo04EKM+hkPoy1gpfauGMkMtstHSARMRGOWto
# OpWTlzhwCvC3kwn1yLUC2qsqKJGnq5qyrKBBew7wxqN6tbNYBF9tE5F0EWsl3Zt1
# VrK4/jE1XNSLB5qUtXIFNbacPcZ1dOiDSuIkXCU3otSxfqBgrveFGoO1XtJ0+3pj
# zbIbPe0o3hY0XZXqNRGKNfjgRFeycqD+kYSCgm9Way8O9AZIB2GPmA256y1eMV7n
# dkum
# SIG # End signature block
