#
# Module manifest for module 'Az.RecoveryServices'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2023/2/3
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.RecoveryServices.psm1'

# Version number of this module.
ModuleVersion = '6.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '5af71f43-17ca-45bd-b534-34524b801ade'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Recovery Services cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.

For more information on Recovery Services Backup, please visit the following: https://docs.microsoft.com/azure/backup/
For more information on Site Recovery, please visit the following: https://docs.microsoft.com/azure/site-recovery/'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'Microsoft.Azure.PowerShell.AutoMapper.dll', 
               'Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Backup.Models.dll', 
               'Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Backup.Helpers.dll', 
               'Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Backup.Logger.dll', 
               'Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Backup.Providers.dll', 
               'Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Backup.ServiceClientAdapter.dll', 
               'Microsoft.Azure.PowerShell.RecoveryServices.Management.Sdk.dll', 
               'Microsoft.Azure.PowerShell.RecoveryServices.Backup.Management.Sdk.dll', 
               'Microsoft.Azure.PowerShell.RecoveryServices.Backup.CrossRegionRestore.Management.Sdk.dll', 
               'Microsoft.Azure.Management.RecoveryServices.SiteRecovery.dll', 
               'System.Configuration.ConfigurationManager.dll', 
               'TimeZoneConverter.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'RecoveryServices.Backup.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Get-AzRecoveryServicesBackupProperty', 
               'Get-AzRecoveryServicesVault', 
               'Get-AzRecoveryServicesVaultSettingsFile', 
               'New-AzRecoveryServicesVault', 'Remove-AzRecoveryServicesVault', 
               'Add-AzRecoveryServicesAsrReplicationProtectedItemDisk', 
               'Edit-AzRecoveryServicesAsrRecoveryPlan', 
               'Get-AzRecoveryServicesAsrAlertSetting', 
               'Get-AzRecoveryServicesAsrEvent', 'Get-AzRecoveryServicesAsrFabric', 
               'Get-AzRecoveryServicesAsrJob', 'Get-AzRecoveryServicesAsrNetwork', 
               'Get-AzRecoveryServicesAsrNetworkMapping', 
               'Get-AzRecoveryServicesAsrPolicy', 
               'Get-AzRecoveryServicesAsrProtectableItem', 
               'Get-AzRecoveryServicesAsrProtectionContainer', 
               'Get-AzRecoveryServicesAsrProtectionContainerMapping', 
               'Get-AzRecoveryServicesAsrRecoveryPlan', 
               'Get-AzRecoveryServicesAsrRecoveryPoint', 
               'Get-AzRecoveryServicesAsrReplicationProtectedItem', 
               'Get-AzRecoveryServicesAsrServicesProvider', 
               'Get-AzRecoveryServicesAsrStorageClassification', 
               'Get-AzRecoveryServicesAsrStorageClassificationMapping', 
               'Get-AzRecoveryServicesAsrVaultContext', 
               'Get-AzRecoveryServicesAsrvCenter', 
               'Import-AzRecoveryServicesAsrVaultSettingsFile', 
               'New-AzRecoveryServicesAsrFabric', 
               'New-AzRecoveryServicesAsrInMageAzureV2DiskInput', 
               'New-AzRecoveryServicesAsrNetworkMapping', 
               'New-AzRecoveryServicesAsrPolicy', 
               'New-AzRecoveryServicesAsrProtectableItem', 
               'New-AzRecoveryServicesAsrProtectionContainer', 
               'New-AzRecoveryServicesAsrProtectionContainerMapping', 
               'New-AzRecoveryServicesAsrRecoveryPlan', 
               'New-AzRecoveryServicesAsrReplicationProtectedItem', 
               'New-AzRecoveryServicesAsrStorageClassificationMapping', 
               'New-AzRecoveryServicesAsrvCenter', 
               'New-AzRecoveryServicesAsrAzureToAzureDiskReplicationConfig', 
               'New-AzRecoveryServicesAsrVMNicConfig', 
               'New-AzRecoveryServicesAsrVMNicIPConfig', 
               'Remove-AzRecoveryServicesAsrFabric', 
               'Remove-AzRecoveryServicesAsrNetworkMapping', 
               'Remove-AzRecoveryServicesAsrPolicy', 
               'Remove-AzRecoveryServicesAsrProtectionContainer', 
               'Remove-AzRecoveryServicesAsrProtectionContainerMapping', 
               'Remove-AzRecoveryServicesAsrRecoveryPlan', 
               'Remove-AzRecoveryServicesAsrReplicationProtectedItem', 
               'Remove-AzRecoveryServicesAsrReplicationProtectedItemDisk', 
               'Remove-AzRecoveryServicesAsrServicesProvider', 
               'Remove-AzRecoveryServicesAsrStorageClassificationMapping', 
               'Remove-AzRecoveryServicesAsrvCenter', 
               'Restart-AzRecoveryServicesAsrJob', 
               'Resume-AzRecoveryServicesAsrJob', 
               'Set-AzRecoveryServicesAsrAlertSetting', 
               'Set-AzRecoveryServicesAsrReplicationProtectedItem', 
               'Set-AzRecoveryServicesAsrVaultContext', 
               'Start-AzRecoveryServicesAsrApplyRecoveryPoint', 
               'Start-AzRecoveryServicesAsrCommitFailoverJob', 
               'Start-AzRecoveryServicesAsrPlannedFailoverJob', 
               'Start-AzRecoveryServicesAsrResynchronizeReplicationJob', 
               'Start-AzRecoveryServicesAsrSwitchAppliance', 
               'Start-AzRecoveryServicesAsrSwitchProcessServerJob', 
               'Start-AzRecoveryServicesAsrTestFailoverCleanupJob', 
               'Start-AzRecoveryServicesAsrTestFailoverJob', 
               'Start-AzRecoveryServicesAsrUnplannedFailoverJob', 
               'Stop-AzRecoveryServicesAsrJob', 
               'Update-AzRecoveryServicesAsrMobilityService', 
               'Update-AzRecoveryServicesAsrNetworkMapping', 
               'Update-AzRecoveryServicesAsrPolicy', 
               'Update-AzRecoveryServicesAsrProtectionContainerMapping', 
               'Update-AzRecoveryServicesAsrProtectionDirection', 
               'Update-AzRecoveryServicesAsrRecoveryPlan', 
               'Update-AzRecoveryServicesAsrServicesProvider', 
               'Update-AzRecoveryServicesAsrvCenter', 
               'Set-AzRecoveryServicesBackupProperty', 
               'Set-AzRecoveryServicesVaultContext', 
               'Backup-AzRecoveryServicesBackupItem', 
               'Get-AzRecoveryServicesBackupManagementServer', 
               'Get-AzRecoveryServicesBackupContainer', 
               'Register-AzRecoveryServicesBackupContainer', 
               'Unregister-AzRecoveryServicesBackupContainer', 
               'Disable-AzRecoveryServicesBackupProtection', 
               'Enable-AzRecoveryServicesBackupProtection', 
               'Enable-AzRecoveryServicesBackupAutoProtection', 
               'Disable-AzRecoveryServicesBackupAutoProtection', 
               'Get-AzRecoveryServicesBackupItem', 
               'Get-AzRecoveryServicesBackupProtectableItem', 
               'Initialize-AzRecoveryServicesBackupProtectableItem', 
               'Get-AzRecoveryServicesBackupJob', 
               'Get-AzRecoveryServicesBackupJobDetail', 
               'Stop-AzRecoveryServicesBackupJob', 
               'Wait-AzRecoveryServicesBackupJob', 
               'Get-AzRecoveryServicesBackupProtectionPolicy', 
               'Get-AzRecoveryServicesBackupRetentionPolicyObject', 
               'Get-AzRecoveryServicesBackupSchedulePolicyObject', 
               'New-AzRecoveryServicesBackupProtectionPolicy', 
               'Remove-AzRecoveryServicesBackupProtectionPolicy', 
               'Set-AzRecoveryServicesBackupProtectionPolicy', 
               'Get-AzRecoveryServicesBackupRecoveryPoint', 
               'Get-AzRecoveryServicesBackupRecoveryLogChain', 
               'Restore-AzRecoveryServicesBackupItem', 
               'Get-AzRecoveryServicesBackupWorkloadRecoveryConfig', 
               'Unregister-AzRecoveryServicesBackupManagementServer', 
               'Get-AzRecoveryServicesBackupRPMountScript', 
               'Disable-AzRecoveryServicesBackupRPMountScript', 
               'Get-AzRecoveryServicesBackupStatus', 
               'Undo-AzRecoveryServicesBackupItemDeletion', 
               'Set-AzRecoveryServicesVaultProperty', 
               'Get-AzRecoveryServicesVaultProperty', 
               'Copy-AzRecoveryServicesVault', 'Update-AzRecoveryServicesVault', 
               'New-AzRecoveryServicesAsrInMageRcmDiskInput', 
               'Start-AzRecoveryServicesAsrCancelFailoverJob', 
               'Test-AzRecoveryServicesDSMove', 
               'Initialize-AzRecoveryServicesDSMove', 
               'Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup', 
               'Move-AzRecoveryServicesBackupRecoveryPoint', 
               'Get-AzRecoveryServicesResourceGuardMapping', 
               'Remove-AzRecoveryServicesResourceGuardMapping', 
               'Set-AzRecoveryServicesResourceGuardMapping'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-AzRecoveryServicesBackupProperties', 
               'Add-ASRReplicationProtectedItemDisk', 'Edit-ASRRP', 
               'Edit-ASRRecoveryPlan', 'Get-ASRAlertSetting', 'Get-ASREvent', 
               'Get-ASRFabric', 'Get-ASRJob', 'Get-ASRNetwork', 
               'Get-ASRNetworkMapping', 'Get-ASRNotificationSetting', 
               'Get-ASRPolicy', 'Get-ASRProtectableItem', 
               'Get-ASRProtectionContainer', 'Get-ASRProtectionContainerMapping', 
               'Get-ASRRP', 'Get-ASRRecoveryPlan', 'Get-ASRRecoveryPoint', 
               'Get-ASRReplicationProtectedItem', 'Get-ASRServicesProvider', 
               'Get-ASRStorageClassification', 
               'Get-ASRStorageClassificationMapping', 'Set-ASRVaultContext', 
               'Set-ASRVaultSettings', 'Get-ASRvCenter', 
               'Get-AzRecoveryServicesAsrNotificationSetting', 
               'Get-AzRecoveryServicesAsrVaultSettings', 'New-ASRFabric', 
               'New-AsrInMageAzureV2DiskInput', 'New-ASRNetworkMapping', 
               'New-ASRPolicy', 'New-ASRProtectableItem', 
               'New-ASRProtectionContainerMapping', 'New-ASRRP', 
               'New-ASRRecoveryPlan', 'New-ASRReplicationProtectedItem', 
               'New-ASRStorageClassificationMapping', 'New-ASRvCenter', 
               'New-ASRVMNicConfig', 'Remove-ASRFabric', 'Remove-ASRNetworkMapping', 
               'Remove-ASRPolicy', 'Remove-ASRProtectionContainerMapping', 
               'Remove-ASRRP', 'Remove-ASRRecoveryPlan', 
               'Remove-ASRReplicationProtectedItem', 'Remove-ASRServicesProvider', 
               'Remove-ASRReplicationProtectedItemDisk', 
               'Remove-ASRStorageClassificationMapping', 'Remove-ASRvCenter', 
               'Restart-ASRJob', 'Resume-ASRJob', 'Set-ASRAlertSetting', 
               'Set-ASRNotificationSetting', 'Set-ASRReplicationProtectedItem', 
               'Set-AzRecoveryServicesAsrNotificationSetting', 
               'Set-AzRecoveryServicesAsrVaultSettings', 
               'Start-ASRApplyRecoveryPoint', 'Start-ASRCommitFailover', 
               'Start-ASRCommitFailoverJob', 'Start-ASRFO', 'Start-ASRPFO', 
               'Start-ASRPlannedFailoverJob', 'Start-ASRResyncJob', 
               'Start-ASRResynchronizeReplicationJob', 
               'Start-ASRSwitchProcessServerJob', 'Start-ASRTFO', 
               'Start-ASRTFOCleanupJob', 'Start-ASRTestFailoverCleanupJob', 
               'Start-ASRTestFailoverJob', 'Start-ASRUnplannedFailoverJob', 
               'Stop-ASRJob', 'Update-ASRMobilityService', 'Update-ASRPolicy', 
               'Update-ASRProtectionContainerMapping', 
               'Update-ASRProtectionDirection', 'Update-ASRRecoveryPlan', 
               'Update-ASRServicesProvider', 'Update-ASRvCenter', 
               'New-ASRInMageRcmDiskInput', 'Start-ASRCancelFailover', 
               'Start-ASRCancelFailoverJob', 'Start-ASRSwitchAppliance'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ResourceManager','ARM','RecoveryServices'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Added support for enable/disable Public Network Access and PrivateEndpoints
* Added support for Immutable Vaults
* Added support for RetainRecoveryPointsAsPerPolicy in Disable-AzRecoveryServicesBackupProtection cmdlet. Now user can suspend backups and retain RPs as per policy
* Added List Recovery Point expiry time
* Added RecoveryServices, RecoveryServices.Backup, RecoveryServices.Backup.CrossRegionRestore management SDK
* Added support for non-UTC time zones with standard policy for workloadType IaasVM, MSSql, AzureFiles'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInrQYJKoZIhvcNAQcCoIInnjCCJ5oCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDYBWWlKkb/2aQd
# mXtMFJtpeUURGRTyqcd9GOoTOuODNaCCDYEwggX/MIID56ADAgECAhMzAAACzI61
# lqa90clOAAAAAALMMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjIwNTEyMjA0NjAxWhcNMjMwNTExMjA0NjAxWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQCiTbHs68bADvNud97NzcdP0zh0mRr4VpDv68KobjQFybVAuVgiINf9aG2zQtWK
# No6+2X2Ix65KGcBXuZyEi0oBUAAGnIe5O5q/Y0Ij0WwDyMWaVad2Te4r1Eic3HWH
# UfiiNjF0ETHKg3qa7DCyUqwsR9q5SaXuHlYCwM+m59Nl3jKnYnKLLfzhl13wImV9
# DF8N76ANkRyK6BYoc9I6hHF2MCTQYWbQ4fXgzKhgzj4zeabWgfu+ZJCiFLkogvc0
# RVb0x3DtyxMbl/3e45Eu+sn/x6EVwbJZVvtQYcmdGF1yAYht+JnNmWwAxL8MgHMz
# xEcoY1Q1JtstiY3+u3ulGMvhAgMBAAGjggF+MIIBejAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUiLhHjTKWzIqVIp+sM2rOHH11rfQw
# UAYDVR0RBEkwR6RFMEMxKTAnBgNVBAsTIE1pY3Jvc29mdCBPcGVyYXRpb25zIFB1
# ZXJ0byBSaWNvMRYwFAYDVQQFEw0yMzAwMTIrNDcwNTI5MB8GA1UdIwQYMBaAFEhu
# ZOVQBdOCqhc3NyK1bajKdQKVMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly93d3cu
# bWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY0NvZFNpZ1BDQTIwMTFfMjAxMS0w
# Ny0wOC5jcmwwYQYIKwYBBQUHAQEEVTBTMFEGCCsGAQUFBzAChkVodHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY0NvZFNpZ1BDQTIwMTFfMjAx
# MS0wNy0wOC5jcnQwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEAeA8D
# sOAHS53MTIHYu8bbXrO6yQtRD6JfyMWeXaLu3Nc8PDnFc1efYq/F3MGx/aiwNbcs
# J2MU7BKNWTP5JQVBA2GNIeR3mScXqnOsv1XqXPvZeISDVWLaBQzceItdIwgo6B13
# vxlkkSYMvB0Dr3Yw7/W9U4Wk5K/RDOnIGvmKqKi3AwyxlV1mpefy729FKaWT7edB
# d3I4+hldMY8sdfDPjWRtJzjMjXZs41OUOwtHccPazjjC7KndzvZHx/0VWL8n0NT/
# 404vftnXKifMZkS4p2sB3oK+6kCcsyWsgS/3eYGw1Fe4MOnin1RhgrW1rHPODJTG
# AUOmW4wc3Q6KKr2zve7sMDZe9tfylonPwhk971rX8qGw6LkrGFv31IJeJSe/aUbG
# dUDPkbrABbVvPElgoj5eP3REqx5jdfkQw7tOdWkhn0jDUh2uQen9Atj3RkJyHuR0
# GUsJVMWFJdkIO/gFwzoOGlHNsmxvpANV86/1qgb1oZXdrURpzJp53MsDaBY/pxOc
# J0Cvg6uWs3kQWgKk5aBzvsX95BzdItHTpVMtVPW4q41XEvbFmUP1n6oL5rdNdrTM
# j/HXMRk1KCksax1Vxo3qv+13cCsZAaQNaIAvt5LvkshZkDZIP//0Hnq7NnWeYR3z
# 4oFiw9N2n3bb9baQWuWPswG0Dq9YT9kb+Cs4qIIwggd6MIIFYqADAgECAgphDpDS
# AAAAAAADMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
# V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
# IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0
# ZSBBdXRob3JpdHkgMjAxMTAeFw0xMTA3MDgyMDU5MDlaFw0yNjA3MDgyMTA5MDla
# MH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMT
# H01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQCr8PpyEBwurdhuqoIQTTS68rZYIZ9CGypr6VpQqrgG
# OBoESbp/wwwe3TdrxhLYC/A4wpkGsMg51QEUMULTiQ15ZId+lGAkbK+eSZzpaF7S
# 35tTsgosw6/ZqSuuegmv15ZZymAaBelmdugyUiYSL+erCFDPs0S3XdjELgN1q2jz
# y23zOlyhFvRGuuA4ZKxuZDV4pqBjDy3TQJP4494HDdVceaVJKecNvqATd76UPe/7
# 4ytaEB9NViiienLgEjq3SV7Y7e1DkYPZe7J7hhvZPrGMXeiJT4Qa8qEvWeSQOy2u
# M1jFtz7+MtOzAz2xsq+SOH7SnYAs9U5WkSE1JcM5bmR/U7qcD60ZI4TL9LoDho33
# X/DQUr+MlIe8wCF0JV8YKLbMJyg4JZg5SjbPfLGSrhwjp6lm7GEfauEoSZ1fiOIl
# XdMhSz5SxLVXPyQD8NF6Wy/VI+NwXQ9RRnez+ADhvKwCgl/bwBWzvRvUVUvnOaEP
# 6SNJvBi4RHxF5MHDcnrgcuck379GmcXvwhxX24ON7E1JMKerjt/sW5+v/N2wZuLB
# l4F77dbtS+dJKacTKKanfWeA5opieF+yL4TXV5xcv3coKPHtbcMojyyPQDdPweGF
# RInECUzF1KVDL3SV9274eCBYLBNdYJWaPk8zhNqwiBfenk70lrC8RqBsmNLg1oiM
# CwIDAQABo4IB7TCCAekwEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFEhuZOVQ
# BdOCqhc3NyK1bajKdQKVMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1Ud
# DwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFHItOgIxkEO5FAVO
# 4eqnxzHRI4k0MFoGA1UdHwRTMFEwT6BNoEuGSWh0dHA6Ly9jcmwubWljcm9zb2Z0
# LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dDIwMTFfMjAxMV8wM18y
# Mi5jcmwwXgYIKwYBBQUHAQEEUjBQME4GCCsGAQUFBzAChkJodHRwOi8vd3d3Lm1p
# Y3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dDIwMTFfMjAxMV8wM18y
# Mi5jcnQwgZ8GA1UdIASBlzCBlDCBkQYJKwYBBAGCNy4DMIGDMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2RvY3MvcHJpbWFyeWNw
# cy5odG0wQAYIKwYBBQUHAgIwNB4yIB0ATABlAGcAYQBsAF8AcABvAGwAaQBjAHkA
# XwBzAHQAYQB0AGUAbQBlAG4AdAAuIB0wDQYJKoZIhvcNAQELBQADggIBAGfyhqWY
# 4FR5Gi7T2HRnIpsLlhHhY5KZQpZ90nkMkMFlXy4sPvjDctFtg/6+P+gKyju/R6mj
# 82nbY78iNaWXXWWEkH2LRlBV2AySfNIaSxzzPEKLUtCw/WvjPgcuKZvmPRul1LUd
# d5Q54ulkyUQ9eHoj8xN9ppB0g430yyYCRirCihC7pKkFDJvtaPpoLpWgKj8qa1hJ
# Yx8JaW5amJbkg/TAj/NGK978O9C9Ne9uJa7lryft0N3zDq+ZKJeYTQ49C/IIidYf
# wzIY4vDFLc5bnrRJOQrGCsLGra7lstnbFYhRRVg4MnEnGn+x9Cf43iw6IGmYslmJ
# aG5vp7d0w0AFBqYBKig+gj8TTWYLwLNN9eGPfxxvFX1Fp3blQCplo8NdUmKGwx1j
# NpeG39rz+PIWoZon4c2ll9DuXWNB41sHnIc+BncG0QaxdR8UvmFhtfDcxhsEvt9B
# xw4o7t5lL+yX9qFcltgA1qFGvVnzl6UJS0gQmYAf0AApxbGbpT9Fdx41xtKiop96
# eiL6SJUfq/tHI4D1nvi/a7dLl+LrdXga7Oo3mXkYS//WsyNodeav+vyL6wuA6mk7
# r/ww7QRMjt/fdW1jkT3RnVZOT7+AVyKheBEyIXrvQQqxP/uozKRdwaGIm1dxVk5I
# RcBCyZt2WwqASGv9eZ/BvW1taslScxMNelDNMYIZgjCCGX4CAQEwgZUwfjELMAkG
# A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
# HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9z
# b2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAxMQITMwAAAsyOtZamvdHJTgAAAAACzDAN
# BglghkgBZQMEAgEFAKCBrjAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgor
# BgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAvBgkqhkiG9w0BCQQxIgQgfc6lBQGM
# ujszvdYqCjV6adBGY6scuHfchqtH/nZ4LmgwQgYKKwYBBAGCNwIBDDE0MDKgFIAS
# AE0AaQBjAHIAbwBzAG8AZgB0oRqAGGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbTAN
# BgkqhkiG9w0BAQEFAASCAQAkjQ74BNqqPhiwXyJ2onSuCV22wR18OkDjGFAzb5Dt
# th984aUIrtRhmWGHsLLvv4xKPQ6vIaq3IxPAs513oEyCCkGoforT+S0VqXOqqCyI
# uKyvT3waPoiblU1UT0a0x6PrcW+ppquxU62yVZfrELIxLHjynhDSoS0B10blpoJK
# KDxZRlKBdfjvIr0iZJoRD+LOOdIfS4lVnxmVheP7ynp8SYY7ifWg2BU3qFyMtqQ9
# pi0vtDBEiHxAsLOeoQ9iy7QuOneGgdOQRUnmVB8ae3xhePvK/lHjlZRGMH708QhO
# TXSV+im6K4RE/vIiusxINdq65ysUTCzNixV0Qh4v+fiUoYIXDDCCFwgGCisGAQQB
# gjcDAwExghb4MIIW9AYJKoZIhvcNAQcCoIIW5TCCFuECAQMxDzANBglghkgBZQME
# AgEFADCCAVUGCyqGSIb3DQEJEAEEoIIBRASCAUAwggE8AgEBBgorBgEEAYRZCgMB
# MDEwDQYJYIZIAWUDBAIBBQAEIAMo87L/0KRuVDNf1T/8bPDYdpfhS6ikOZcfDwEq
# OEYuAgZjxotepBsYEzIwMjMwMjAzMTE0MDExLjQ2MlowBIACAfSggdSkgdEwgc4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKTAnBgNVBAsTIE1p
# Y3Jvc29mdCBPcGVyYXRpb25zIFB1ZXJ0byBSaWNvMSYwJAYDVQQLEx1UaGFsZXMg
# VFNTIEVTTjo0NjJGLUUzMTktM0YyMDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgU2VydmljZaCCEV8wggcQMIIE+KADAgECAhMzAAABpAfP44+jum/WAAEA
# AAGkMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MB4XDTIyMDMwMjE4NTExOFoXDTIzMDUxMTE4NTExOFowgc4xCzAJBgNVBAYTAlVT
# MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKTAnBgNVBAsTIE1pY3Jvc29mdCBPcGVy
# YXRpb25zIFB1ZXJ0byBSaWNvMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjo0NjJG
# LUUzMTktM0YyMDElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vydmlj
# ZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMBHjgD6FPy81PUhcOIV
# Gh4bOSaq634Y+TjW2hNF9BlnWxLJCEuMiV6YF5x6YTM7T1ZLM6NnH0whPypiz3bV
# ZRmwgGyTURKfVyPJ89R3WaZ/HMvcAJZnCMgL+mOpxE94gwQJD/qo8UquOrCKCY/f
# cjchxV8yMkfIqP69HnWfW0ratk+I2GZF2ISFyRtvEuxJvacIFDFkQXj3H+Xy9IHz
# Nqqi+g54iQjOAN6s3s68mi6rqv6+D9DPVPg1ev6worI3FlYzrPLCIunsbtYt3Xw3
# aHKMfA+SH8CV4iqJ/eEZUP1uFJT50MAPNQlIwWERa6cccSVB5mN2YgHf8zDUqQU4
# k2/DWw+14iLkwrgNlfdZ38V3xmxC9mZc9YnwFc32xi0czPzN15C8wiZEIqCddxbw
# imc+0LtPKandRXk2hMfwg0XpZaJxDfLTgvYjVU5PXTgB10mhWAA/YosgbB8KzvAx
# XPnrEnYg3XLWkgBZ+lOrHvqiszlFCGQC9rKPVFPCCsey356VhfcXlvwAJauAk7V0
# nLVTgwi/5ILyHffEuZYDnrx6a+snqDTHL/ZqRsB5HHq0XBo/i7BVuMXnSSXlFCo3
# On8IOl8JOKQ4CrIlri9qWJYMxsSICscotgODoYOO4lmXltKOB0l0IAhEXwSSKID5
# QAa9wTpIagea2hzjI6SUY1W/AgMBAAGjggE2MIIBMjAdBgNVHQ4EFgQU4tATn6z4
# CBL2xZQd0jjN6SnjJMIwHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIw
# XwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
# cy9jcmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3Js
# MGwGCCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3Nv
# ZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
# JTIwMjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADATBgNVHSUEDDAKBggrBgEFBQcD
# CDANBgkqhkiG9w0BAQsFAAOCAgEACVYcUNEMlyTuPDBGhiZ1U548ssF6J2g9QElW
# Eb2cZ4dL0+5G8721/giRtTPvgxQhDF5rJCjHGj8nFSqOE8fnYz9vgb2YclYHvkoK
# WUJODxjhWS+S06ZLR/nDS85HeDAD0FGduAA80Q7vGzknKW2jxoNHTb74KQEMWiUK
# 1M2PDN+eISPXPhPudGVGLbIEAk1Goj5VjzbQuLKhm2Tk4a22rkXkeE98gyNojHlB
# hHbb7nex3zGBTBGkVtwt2ud7qN2rcpuJhsJ/vL/0XYLtyOk7eSQZdfye0TT1/qj1
# 8iSXHsIXDhHOuTKqBiiatoo4Unwk7uGyM0lv38Ztr+YpajSP+p0PEMRH9RdfrKRm
# 4bHV5CmOTIzAmc49YZt40hhlVwlClFA4M+zn3cyLmEGwfNqD693hD5W3vcpnhf3x
# hZbVWTVpJH1CPGTmR4y5U9kxwysK8VlfCFRwYUa5640KsgIv1tJhF9LXemWIPEnu
# w9JnzHZ3iSw5dbTSXp9HmdOJIzsO+/tjQwZWBSFqnayaGv3Y8w1KYiQJS8cKJhwn
# hGgBPbyan+E5D9TyY9dKlZ3FikstwM4hKYGEUlg3tqaWEilWwa9SaNetNxjSfgah
# 782qzbjTQhwDgc6Jf07F2ak0YMnNJFHsBb1NPw77dhmo9ki8vrLOB++d6Gm2Z/jD
# pDOSst8wggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3
# DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
# A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIw
# MAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAx
# MDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVT
# MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
# LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
# 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/
# XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1
# hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7
# M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3K
# Ni1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy
# 1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF80
# 3RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQc
# NIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahha
# YQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkL
# iWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
# 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
# CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUp
# zxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBT
# MFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jv
# c29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYI
# KwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGG
# MA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186a
# GMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3Br
# aS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsG
# AQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
# AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
# OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYA
# A7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbz
# aN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6L
# GYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3m
# Sj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0
# SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxko
# JLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFm
# PWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC482
# 2rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7
# vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIC0jCC
# AjsCAQEwgfyhgdSkgdEwgc4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
# dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xKTAnBgNVBAsTIE1pY3Jvc29mdCBPcGVyYXRpb25zIFB1ZXJ0byBSaWNv
# MSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjo0NjJGLUUzMTktM0YyMDElMCMGA1UE
# AxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIaAxUA
# NBwo4pNrfEL6DVo+tw96vGJvLp+ggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEG
# A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
# cm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFt
# cCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIFAOeGybwwIhgPMjAyMzAyMDMwMzQ2
# MDRaGA8yMDIzMDIwNDAzNDYwNFowdzA9BgorBgEEAYRZCgQBMS8wLTAKAgUA54bJ
# vAIBADAKAgEAAgIIggIB/zAHAgEAAgIRkTAKAgUA54gbPAIBADA2BgorBgEEAYRZ
# CgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0G
# CSqGSIb3DQEBBQUAA4GBAFKhEODXn7JoHUXCmelfAYfnsTkUXR1O2daoD4NLluH1
# YtPHh6zQZmhkgqfKrC7emDRy0Ov9qqso9dep/FnE55kmuEAZWpbW6IrVrXn97Sbn
# r1rnqTFnB4lL4hwGAihf6Fw2gWovDvAl7TnNHfHFSlmq9kTcYQMwOvH9VJLTE9eu
# MYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
# AAGkB8/jj6O6b9YAAQAAAaQwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJ
# AzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgWh1EhzuLpUescLhNrL9/
# BblDU6Gv0qoiXmfTy1wqU7gwgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCAF
# /OCjISZwpMBJ8MJ3WwMCF3qOa5YHFG6J4uHjaup5+DCBmDCBgKR+MHwxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABpAfP44+jum/WAAEAAAGkMCIEIOuS
# g7LidCUK5OyH+KGFPHnt3etB9dYkGnWaSRUiGyvuMA0GCSqGSIb3DQEBCwUABIIC
# AJYJ6tcmf76syNxO+fr1ppcfBTAmM6eYS8dkis6gfxFW5CABUQIMFstVRIdFB1Gv
# P7qHhMcLCVbcH+eXz/ms3+wj1DIa9otMM7AQdNIm1lq0h47jHoUqhS5b3TYpngHq
# yV+SVuw8OiO3uVqDIiy0qmtVo8PhKriMTS3qAx+c5/m8yVIHHy6vK3pH3QtZvRF2
# 08mfyAwlUYP6RqHsugG43IyrCzL+0UHZpd8Bgv1zgW2IyHVBqp3dpctxeCj8Y0xO
# yXyhzpDTasUcWeDOYwLxjuSTzMeOv9/gd/xFeRjfc3/HvmsFUQIaKmm+/M0moIQK
# lI9BxJ9TB663B8lBpjetmG3DUzRJu2sI9Dn+x8ITnAv87nTjG60MQegBAy8WlxnJ
# VHdUj1QM7yuKVXtcQxSJPYZwPaVQXa9Ybj/eDhZNLdEZQZAGIpjp/oDzL1/nqDJh
# rwbe5LimoR7eg2TtwIyqCBZDzMNdHrcXT1as4cxSE4G/KtR/eAes3WTe2MI/Z7cl
# EKfD6VEntKTzfWp2LEHoPbtFn9Kn2Btthhu+kFJjA9myb02l38ripY5xNqg9YKxa
# HB+wWhBSDm8r+ciMEPTjg/RplfbQc678FMTNILImgH8R/dY0PW9b065z/KX4hNeS
# L3sldJzcmFO4vjZV25OniiyA8az34ewhGNlhYLz5klGG
# SIG # End signature block
